base:
  random_state: 42
  image_size: 224
  batch_size: 16

data:
  raw_dataset_path: "data/raw"
  train_path: "data/train"
  val_path: "data/val"
  augmented_path: "data/augmented"
  # Переключатель: использовать обычные данные ("data/train") или аугментированные ("data/augmented")
  current_train_data: "data/train"

train:
  epochs: 3
  learning_rate: 0.001
  # Выбор модели: simple_cnn, resnet18, mobilenet
  model_type: "simple_cnn"